[package]
name = "cargo-chrono"
version = "0.1.0"
authors = ["Niko Matsakis <niko@alum.mit.edu>"]

[dependencies]
docopt = "0.6.82"
git2 = "0.4.4"
regex = "0.1.73"
rustc-serialize = "0.3.19"
log = "0.3"
env_logger = "0.3"
csv = "0.14.7"
error-chain = { version = "0.7.0", git = "https://github.com/brson/error-chain", branch = "fixes" }